title: "Jai Vivek Nagaraj"
email: jai.v.nagaraj@gmail.com
description: "When you say normal... what does that even mean?"
baseurl: "" # set to "/repo" if deploying to a project page
url: "https://jaiNagaraj.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Silence Sass deprecation warnings from minima theme
sass:
  quiet_deps: true

author:
  name: "Jai Nagaraj"
  github: "jaiNagaraj"

markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
